### ISSUE TITLE
Server Connection 

### ISSUE THREAD

**Issue by deepakmalhotra633** [openshopio/openshop.io-android#41]
can you tell me how to connect from server(if i m using magento )and how to configure apiary documantation

**Comment by webmatrix** [comment]
You can configure your Magento API and define API endpoints in EndPoints.java.As of there is no documentation for required JSON formats. So you need to figure it out or modify openshop code to integrate with Magento API.
You can
https://github.com/openshopio/openshop.io-android/blob/master/app/src/main/java/bf/io/openshop/api/EndPoints.java

**Comment by coolhaka** [comment]
How can i connect this app template to my opencart 1.5.6.4  based site?

**Comment by webmatrix** [comment]
@coolhaka  you need to develop Opencart extension which will communicate with openshop app

**Comment by coolhaka** [comment]
I don't know how to do that. Can anyone help me to do it.

**Comment by rahulsinghmzp** [comment]
@webmatrix  I hav my wordpress woocommerce website showing json, i hav  added facebook_ap_id and  google gcm android key but i am unable to get ORGANIZATION_ID. Please help me to get my ORGANIZATION_ID. i want to use my woocommerce site data in the app, it is givving following error

07:52:17.634 915-1138/com.example.rahul.myshop E/Volley: [35346] BasicNetwork.performRequest: Unexpected response code 404 for https://www.mywebsite.com/wp-json/wc/v2/4/shops
03-03 07:52:17.684 915-1138/com.example.rahul.myshop E/GsonRequest: GsonRequest URL: https://www.mywebsite.com/wp-json/wc/v2/4/shops. ERROR: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
03-03 07:52:21.194 915-1111/com.example.rahul.myshop V/FA: Inactivity, disconnecting from the service
03-03 08:05:58.914 915-6306/com.example.rahul.myshop V/FA: Using measurement service
03-03 08:05:58.914 915-6306/com.example.rahul.myshop V/FA: Connecting to remote service
03-03 08:05:58.944 915-6306/com.example.rahul.myshop V/FA: Activity resumed, time: 1120726142
03-03 08:05:58.944 915-6306/com.example.rahul.myshop D/FA: Connected to remote service
03-03 08:05:58.944 915-6306/com.example.rahul.myshop V/FA: Processing queued up service tasks: 1
03-03 08:06:03.174 915-6306/com.example.rahul.myshop V/FA: Recording user engagement, ms: 4262
03-03 08:06:03.184 915-6306/com.example.rahul.myshop V/FA: Activity paused, time: 1120730404
03-03 08:06:03.194 915-6306/com.example.rahul.myshop I/FA: Tag Manager is not found and thus will not be used
03-03 08:06:03.214 915-6306/com.example.rahul.myshop D/FA: Logging event (FE): _e, Bundle[{_o=auto, _et=4262, _sc=SplashActivity, _si=6343153134171536281}]
03-03 08:06:05.114 915-915/com.example.rahul.myshop V/FA: onActivityCreated
03-03 08:06:05.124 915-915/com.example.rahul.myshop D/SplashActivity: Extra bundle detected.
03-03 08:06:05.124 915-915/com.example.rahul.myshop D/SplashActivity: Nothing special.
03-03 08:06:05.124 915-915/com.example.rahul.myshop D/rahul: yolo
03-03 08:06:05.124 915-915/com.example.rahul.myshop E/SettingsMy: SettingsMy - Returned null shop
03-03 08:06:05.124 915-915/com.example.rahul.myshop D/SplashActivity: Missing active shop. Show shop selection.
03-03 08:06:05.154 915-6306/com.example.rahul.myshop V/FA: Activity resumed, time: 1120732379
03-03 08:06:05.164 915-1137/com.example.rahul.myshop D/libc: [NET] android_getaddrinfofornetcontext+,hn 14(0x7777772e7a6572),sn(),hints(known),family 0,flags 1024, proc=com.example.rahul.myshop
03-03 08:06:05.164 915-1137/com.example.rahul.myshop D/libc: [NET] android_getaddrinfo_proxy get netid:0
03-03 08:06:05.164 915-1137/com.example.rahul.myshop D/libc: [NET] android_getaddrinfo_proxy-, success
03-03 08:06:06.514 915-1137/com.example.rahul.myshop E/Volley: [35345] BasicNetwork.performRequest: Unexpected response code 404 for https://www.mywebsite.com/wp-json/wc/v2/4/shops
03-03 08:06:06.514 915-1137/com.example.rahul.myshop E/GsonRequest: GsonRequest URL: https://www.mywebsite.com/wp-json/wc/v2/4/shops. ERROR: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
03-03 08:06:06.524 915-915/com.example.rahul.myshop E/MsgUtils: ShowMessage exception
                                                                org.json.JSONException: No value for body
                                                                    at org.json.JSONObject.get(JSONObject.java:389)
                                                                    at org.json.JSONObject.getJSONArray(JSONObject.java:584)
                                                                    at com.example.rahul.myshop.utils.MsgUtils.showMessage(MsgUtils.java:53)
                                                                    at com.example.rahul.myshop.utils.MsgUtils.logAndShowErrorMessage(MsgUtils.java:41)
                                                                    at com.example.rahul.myshop.ux.SplashActivity$7.onErrorResponse(SplashActivity.java:352)
                                                                    at com.android.volley.Request.deliverError(Request.java:564)
                                                                    at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:168)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5885)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
03-03 08:06:06.594 915-6306/com.example.rahul.myshop V/FA: Recording user engagement, ms: 1443
03-03 08:06:06.604 915-6306/com.example.rahul.myshop V/FA: Activity paused, time: 1120733822

Please help how to get ORGANIZATION-ID

**Comment by ZelvaJan** [comment]
Partially solved by connecting to apiary mock server https://bfashionapibfversion.docs.apiary.io/# there you can get some idea about dataStructure. Generally speaking this is just mobile aplication, you have to write your own server which will handle all the logic and data for specific store -> you can remove organization id, if you plan to use it just for your store.
