### ISSUE TITLE
How to connect?

### ISSUE THREAD

**Issue by arthuravner** [openshopio/openshop.io-android#67]
Hello!

I am trying to run the app openshop and I followed all steps on "https://github.com/openshopio/openshop.io-android" but "How to connect". 

Can someone please give me detailed information about this topic?

This is the error I get when trying to run the app
03-02 00:17:05.335 7660-7660/br.com.organicoshop E/MsgUtils: java.net.ConnectException: Failed to connect to /77.93.198.186:80
                                                             java.lang.NullPointerException: Attempt to read from field 'byte[] com.android.volley.NetworkResponse.data' on a null object reference
                                                                 at br.com.organicoshop.utils.MsgUtils.logAndShowErrorMessage(MsgUtils.java:40)
                                                                 at br.com.organicoshop.ux.SplashActivity$7.onErrorResponse(SplashActivity.java:349)
                                                                 at com.android.volley.Request.deliverError(Request.java:564)
                                                                 at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:145)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:7007)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

I also don't know how obtain the Organization ID.

**Comment by rahulsinghmzp** [comment]
I hav my wordpress woocommerce website showing json, i hav connected with facebook for ap id and with google for android key but i am unable to get ORGANIZATION_ID. Please help me to get my ORGANIZATION_ID.

**Comment by ZelvaJan** [comment]
Partially solved by connecting to apiary mock server https://bfashionapibfversion.docs.apiary.io/# Generally speaking this is just mobile aplication, you have to write your own server which will handle all the logic ad data for specific store.
